config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/logout', to: 'devise/sessions#destroy', as: :logout
  end

  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
require_relative 'application_record'

class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comment_counter

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_like_counter

  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :title, presence: { message: 'Title can\'t be blank' }, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  after_save :update_post_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    author.increment!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :name, presence: { message: 'Name can\'t be blank' }
  validates :post_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(author_id: current_user.id, post_id: params[:post_id], **comment_params)

    if @comment.save
      flash[:notice] = 'Your comment added successfully'
      redirect_to "/users/#{current_user.id}/posts/#{params[:post_id]}"
    else
      flash[:alert] = 'Opps, something went wrong, try again!'
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.new(author_id: current_user.id, post_id: params[:post_id])

    if @like.save
      flash[:notice] = 'Liked successfully'
    else
      flash.now[:alert] = 'Oops, something wrong'
    end
    redirect_to "/users/#{@like.author_id}/posts/#{@like.post_id}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: @user.id)
  end

  def show
    @post = Post.includes(:author, :comments, :likes).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(author_id: current_user.id, **post_params)

    if @post.save
      flash[:success] = 'Post created successfully'
      redirect_to user_posts_path(params[:user_id])
    else
      flash[:alert] = 'Something went wrong. Please try again!'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with model: @comment, url: user_post_comments_path , class: 'post-form box-border' do |f| %>
    <%= f.label :text, 'Text: ', { class: "post-form-label"} %>
    <%= f.text_area :text, { class: "post-form-field" } %>
    <%= f.submit 'Submit', class: 'post-form-submit' %>
<% end %>

<% if flash[:alert] %>
  <p><%= flash[:alert] %></p>
<% end %>

app/views/comments/new.html.erb
<h1> Add a comment</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_path, class: 'post-form box-border' do |f| %>
    <%= f.label :title, 'Title: ', { class: "post-form-label" }%>
    <%= f.text_field :title, { class: "post-form-field" }%>
    <%= f.label :text, 'Text: ', { class: "post-form-label" }%>
    <%= f.text_area :text, { class: "post-form-field" } %>
    <%= f.submit 'Submit', class: 'post-form-submit' %>
<% end %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'posts_styles'%>
<h1>Posts of <%= @user.name %></h1>
<section class='user-posts'>
<section class='user-detail box-border'>
  <%= image_tag(@user.photo) %>
  <div class='user-info'>
    <h2 class='user-name'><%= @user.name %></h2>
    <br>
    <p class='post-btn'>
      <%= link_to 'Create a new post', new_user_post_path %>
    </p>
    <p class= 'user-posts'>Number of posts: <%= @user.post_counter %></p>
  </div>
</section>
<section class='posts-list'>
  <% @posts.each do |post| %>
    <div class='box-border'>
     <article class='posts box-border'>
          <h2><%= "#{post.title}" %></h2>
          <br>
          <p><%= post.text%></p>
          <%= link_to user_post_path(@user.id, post.id) do %>
            <p class='post-btn'>Show more</p>
          <% end %>
          <p class='post-reactions'><%= "Comments: #{post.comments_counter}, Likes: #{post.likes_counter}"%></p>
        </article>
      <div class='comments box-border'>
        <h3>Comments</h3>
        <% post.recent_comments.each do |comment| %>
          <div class='comment'>
            <p class='user-comment'><%= comment.author.name %>: </p>
            <p class='comment-text'><%= comment.text %></p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</section>
</section>

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'posts_styles'%>

<h1>Create new post</h1>
<%= render 'form'%>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'posts_styles'%>

<h1>Show more Details of Post by <%= @post.author.name %></h1>
<% if @post %>
    <section class='post-list'>

       <article class='posts box-border'>
        <h2 class='post-title'>"<%= @post.title %>" by <%= @post.author.name %></h2>
        <br>
          <p><%= @post.text %></p>
        <div class="likes-comments">
          <%= link_to new_user_post_comment_path(@post.author_id, @post.id) do %>
              <p class="post-btn"><%= "Add Comment" %></p>
            <% end %>
          <%= form_with url: user_post_likes_path(@post.author_id, @post.id) do |form| %>
            <p class="post-btn"><%= form.submit "Like" %></p>
          <% end %>
        </div>
          <p class='post-reactions'><%= "Comments: #{@post.comments_counter}, Likes: #{@post.likes_counter}"%></p>
        </article>
         <div class='comments box-border'>
        <h3>Comments</h3>
        <% @post.comments.each do |comment| %>
          <div class='comment'>
            <h3 class='user-comment'><%= comment.author.name %>: </h3>
            <p class='comment-text'><%= comment.text %></p>
          </div>
        <% end %>
      </div>
      </div>
    </section>
<% else %>
  <h1>Post not found</h1>
<% end %>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'users_styles'%>

<h1> List of All Users </h1>

<section class='users'>
   <% @users.each do |user| %>
    <%= link_to user_path(user.id) do %>
     <div class='user box-border'>
       <%= image_tag(user.photo, class: 'user-photo') %>
       <div class='user-info'>
         <h2><%= user.name %></h2> <br>
         <p>Number of posts: <%= user.post_counter %></p>
       </div>
     </div> 
     <% end %>
   <% end %>
</section>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'users_styles'%>

<h1>Details of <%= @user.name %></h1>

<section class='user-details'>
  <div class='user-detail box-border' >
    <%= image_tag(@user.photo, class: 'user-photo') %>
    <div class='user-info'>
      <h2><%= @user.name %></h2> <br>
       <p class='post-btn'>
      <%= link_to 'Create a new post', new_user_post_path(@user.id) %>
    </p>
      <p>Number of posts: <%= @user.post_counter %></p>
    </div>
  </div>

  <div class='box-border'>
    <h2>Bio</h2>
    <p><%= @user.bio%></p>
  </div>
  <section class='posts-section'>
    <% @user.recent_posts.each_with_index do |post, index| %>
        <%= link_to user_posts_path(@user.id) do %>
        <article class='posts box-border'>
          <h2><%= "#{index+1} - #{post.title}" %></h2>
          <br>
          <p><%= post.text%></p>
          <p class='post-reactions'><%= "Comments: #{post.comments_counter}, Likes: #{post.likes_counter}"%></p>
        </article>
        <% end %>
    <% end %>
  </section>

</main>